linters-settings:
  govet:
    check-shadowing: true
  funlen:
    lines: 100
    statements: 60
  gocognit:
    min-complexity: 40
  gocyclo:
    min-complexity: 15
  maligned:
    suggest-new: true
  goconst:
    min-len: 5
    min-occurrences: 3
  misspell:
    locale: US
  lll:
    line-length: 256
  goimports:
    local-prefixes: github.com/kopia/kopia
  gocritic:
    enabled-tags:
      - diagnostic
      - performance
      - style
      - opinionated
      - experimental
    disabled-checks:
      - wrapperFunc
      - whyNoLint
linters:
  enable-all: true
  disable:
    - maligned
    - prealloc
    - gochecknoglobals
    - gochecknoinits
    - whitespace
    - nlreturn
    - testpackage

run:
  skip-dirs:
    - test/testdata_etc

issues:
  exclude-use-default: false
  exclude-rules:
    - path: _test\.go|testing|test_env
      linters:
      - gomnd
      - gocognit
      - funlen
      - errcheck
      - gosec
      - nestif
      - goerr113
    - text: "Magic number: 1e"
      linters:
      - gomnd
    - text: "unnecessaryDefer"
      linters: gocritic
    - text: "filepathJoin"
      linters: gocritic
    - text: "weak cryptographic primitive"
      linters:
        - gosec
    - text: "lines are duplicate of"
      linters:
        - dupl
    - text: "Line contains TODO"
      linters:
        - godox 
    - text: ".*Magic number\\: [01],"
      linters:
        - gomnd
    - text: "Errors unhandled"
      linters:
        - gosec
    - path: cli
      linters:
      - gochecknoglobals

# golangci.com configuration
# https://github.com/golangci/golangci/wiki/Configuration
service:
  golangci-lint-version: 1.24.x # use the fixed version to not introduce new linters unexpectedly

