# This is an example goreleaser.yaml file with some sane defaults.
# Make sure to check the documentation at http://goreleaser.com
before:
  hooks:
    - make html-ui-bindata
builds:
- env:
  - CGO_ENABLED=0
  goos:
  - linux
  - darwin
  - windows
  goarch:
    - amd64
    - arm
    - arm64
  flags:
    - -tags=embedhtml
  ldflags:
  - -s -w -X "github.com/kopia/kopia/repo.BuildVersion={{.Version}}" -X "github.com/kopia/kopia/repo.BuildInfo={{.Commit}}"
release:
  draft: true
archives:
  - id: default
    replacements:
      darwin: macOS
      linux: linux
      windows: windows
      amd64: x64
    name_template: "{{ .ProjectName }}-{{ .Version }}-{{ .Os }}-{{ .Arch }}"
    wrap_in_directory: true
    format_overrides:
    - goos: windows
      format: zip
    files:
      - LICENSE
      - README.md
checksum:
  name_template: 'checksums.txt'
snapshot:
  name_template: '{{ .Env.KOPIA_VERSION_NO_PREFIX }}'
nfpms:
  - homepage: https://kopia.io
    vendor: Kopia Project
    maintainer: Kopia Project <kopia-pmc@googlegroups.com>
    description: Fast and secure open source backup.
    license: Apache 2.0
    file_name_template: "{{ .ProjectName }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}"
    replacements:
      arm: armhf
    formats:
    - deb
    - rpm
    bindir: /usr/bin
brews:
  - homepage: "https://kopia.io"
    tap:
      owner: kopia
      name: homebrew-kopia
    description: "Fast and secure open source backup."
    install:
      bin.install "kopia"
signs:
  -
    artifacts: checksum
    args: ["-a", "--output", "${signature}", "--detach-sign", "${artifact}"]
changelog:
  filters:
    exclude:
    - '^docs:'
    - '^test:'
