# This is an example goreleaser.yaml file with some sane defaults.
# Make sure to check the documentation at http://goreleaser.com
builds:
- env:
  - CGO_ENABLED=0
  goos:
  - linux
  - darwin
  - windows
  goarch:
    - amd64
    - arm
    - arm64
  ldflags:
  - -s -w -X "github.com/kopia/repo.BuildVersion={{.Version}}" -X "github.com/kopia/repo.BuildInfo={{.Commit}}"
archives:
  - id: default
    replacements:
      darwin: macOS
      linux: linux
      windows: windows
      amd64: x64
    name_template: "{{ .ProjectName }}-{{ .Version }}-{{ .Os }}-{{ .Arch }}"
    wrap_in_directory: true
    format_overrides:
    - goos: windows
      format: zip
    files:
      - LICENSE
      - README.md
checksum:
  name_template: 'checksums.txt'
snapshot:
  name_template: "{{ .Tag }}-next"
nfpm:
  homepage: https://kopia.io
  vendor: Kopia Project
  maintainer: Jarek Kowalski <jaak@jkowalski.net>
  description: Fast and secure open source backup.
  license: Apache 2.0
  formats:
  - deb
  - rpm
  bindir: /usr/bin
brew:
  github:
    owner: kopia
    name: homebrew-kopia
  homepage: "https://kopia.io"
  description: "Fast and secure open source backup."
sign:
  artifacts: checksum
changelog:
  sort: asc
  filters:
    exclude:
    - '^docs:'
    - '^test:'
