style: github
template: CHANGELOG.tpl.md
info:
  title: CHANGELOG
  repository_url: https://github.com/kopia/kopia
options:
  commits:
    filters:
      Type:
        - feat
        - fix
        - perf
        - refactor
        - build
  commit_groups:
    sort_by: Custom
    group_by: "Scope"
    title_maps:
      # must match .github/workflows/check-pr-title.yml
      # app|cli|ui|repository|server|providers|deps|deps-dev|site|ci|infra|general
      kopiaui: KopiaUI Desktop App
      cli: Command-Line Interface
      ui: Graphical User Interface
      ci: Continuous Integration
      lint: Linter
      deps: Runtime Dependencies
      deps-dev: Development Dependencies
      infra: Infrastructure
      general: General Improvements
    title_order:
      - cli
      - kopiaui
      - general
      - repository
      - server
      - providers
      - testing
      - lint
      - deps
      - deps-dev
      - infra
  header:
    pattern: "^(\\w*)(?:\\(([\\w\\$\\.\\-\\*\\s]*)\\))?\\:\\s(.*)$"
    pattern_maps:
      - Type
      - Scope
      - Subject
  notes:
    keywords:
      - BREAKING CHANGE